In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


dataset = pd.read_csv('project1.csv')

In [2]:
dataset = dataset.dropna()

In [3]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
data=[]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jayanth\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
for i in range(0,514):
        text=dataset['text'][i]
        text = re.sub('[^a-zA-Z]', ' ', text)
        text = text.lower()
        text = text.split()
        text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
        text = ' '.join(text)
        data.append(text)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(data).toarray()

In [6]:
y = dataset.iloc[:,0].values

In [7]:
X.shape

(514, 1487)

In [8]:
y.shape

(514,)

In [9]:
from sklearn.preprocessing import LabelEncoder
lb1=LabelEncoder()

y =lb1.fit_transform(y)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [15]:
X_test.shape

(103, 1487)

In [16]:
y.shape

(514,)

In [17]:

from keras.models import Sequential
from keras.layers import Dense
model = Sequential()

In [18]:
model.add(Dense(output_dim = 1000, init = 'uniform', activation = 'relu', input_dim = 1487))

model.add(Dense(output_dim = 1000, init = 'uniform', activation = 'relu'))

model.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])




C:\Users\Jayanth\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=1487, units=1000, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
C:\Users\Jayanth\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=1000, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Jayanth\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """


In [19]:
model.fit(X_train,y_train,batch_size=20,epochs=10)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
411/411 [==============================] - 2s 5ms/step - loss: 0.6356 - acc: 0.6180
Epoch 2/10
411/411 [==============================] - 1s 2ms/step - loss: 0.2533 - acc: 0.9221
Epoch 3/10
411/411 [==============================] - 1s 2ms/step - loss: 0.0297 - acc: 0.9927
Epoch 4/10
411/411 [==============================] - 1s 2ms/step - loss: 0.0084 - acc: 0.9976
Epoch 5/10
411/411 [==============================] - 1s 2ms/step - loss: 0.0027 - acc: 1.0000
Epoch 6/10
411/411 [==============================] - 1s 2ms/step - loss: 0.0011 - acc: 1.0000
Epoch 7/10
411/411 [==============================] - 1s 2ms/step - loss: 8.0056e-04 - acc: 1.0000
Epoch 8/10
411/411 [==============================] - 1s 2ms/step - loss: 5.9443e-04 - acc: 1.0000
Epoch 9/10
411/411 [==============================] - 1s 2ms/step - loss: 4.6724e-04 - acc: 1.0000
Epoch 10/10
411/411 [==============================] - 1s 2ms/step - loss: 3.7935e-04

In [20]:
y_pred = model.predict(X_test)


In [21]:
y_pred =y_pred>0.5

In [22]:
y_pred

array([[False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [23]:
y_test

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1])

In [25]:
r = model.predict(cv.transform(["gitam is bad"]))

In [26]:
r=r>0.5

In [27]:
r

array([[False]])

In [93]:
from tkinter import *
text1 = []
data1 = []
top = Tk()
top.geometry("550x300+300+150")
top.resizable(width=True, height=True)

L1 = Label(top, text="Enter Text For Prediction")
L1.pack()
E1 = Entry(top, bd =5)
E1.pack()

def predict():
    print("Prediction on progress..")
    entered_input=E1.get()
    print("Entered Input",entered_input)
    type(entered_input)
    for i in entered_input:
        text1.append(i)
    
        
                 
    prediction = model.predict(cv.transform(text1))
    print(prediction)
    L2 = Label(top, text="Prediction: "+ str(prediction))
    L2.pack()
    
B = Button(top, text ="Predict", command = predict)
B.pack()
top.mainloop()


Prediction on progress..
Entered Input jhh
[[0.68329513]
 [0.68329513]
 [0.68329513]]


good

In [30]:
y_pred = model.predict(X_test)
